version: '3.8'

services:
  backend:
    image: node:18
    working_dir: /workspace/backend
    volumes:
      - ../backend:/workspace/backend
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: node:18
    working_dir: /workspace/frontend
    volumes:
      - ../frontend:/workspace/frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
